### ISSUE TITLE
web driver issue

### ISSUE THREAD

**Issue by justasknunes** [RGV2/InstaBot#1]
what should I do next ?

`python3 InstagramBot.py`

`Traceback (most recent call last):
  File "InstagramBot.py", line 3, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
ModuleNotFoundError: No module named 'webdriver_manager'`

thanks

**Comment by RGV2** [comment]
hit `pip install webdriver_manager` in terminal, then rerun the code.

**Comment by RGV2** [comment]
> what should I do next ?
> 
> `python3 InstagramBot.py`
> 
> `Traceback (most recent call last): File "InstagramBot.py", line 3, in <module> from webdriver_manager.chrome import ChromeDriverManager ModuleNotFoundError: No module named 'webdriver_manager'`
> 
> thanks

hit `pip install webdriver_manager` in terminal, then rerun the code.
